language: c

matrix:
 include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew outdated automake || brew upgrade automake && brew outdated lcov || brew upgrade lcov; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ./get-aclocal.sh && pip install --user cpp-coveralls && sudo apt-get install lcov; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod u+x setup.sh && ./setup.sh && mkdir build && cd build && cmake ../ && make; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod u+x setup.sh && ./setup.sh && mkdir build && cd build && cmake ../ && make; fi
after_success:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi
