language: c

matrix:
 include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.1
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.1
      compiler: clang
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew outdated automake || brew upgrade automake; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ./get-aclocal.sh && pip install --user cpp-coveralls; fi
script: 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod u+x setup.sh && ./setup.sh && make && make build-tests && make test-all; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod u+x setup.sh && ./setup.sh && make COVERAGE=true && make COVERAGE=true build-tests && make test-all; fi
after_success:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi
