
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: c
      compiler: clang
    - os: osx
      osx_image: xcode7.1
      language: c
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.1
      language: c
      compiler: clang
    - os: linux
      language: c
      compiler: gcc
      env:
        global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
          - secure: "RsA1AulD02Y8VMGZCKtfYO61cr8N8LW9OytxZD5qxjmA0P0VnxrsY59yTrJ4psLATjYDOTXq6E4KyJy8IV2N3jkgxgJgob/IalAYkGnBJDRkSWXCk8cW24KvMtMMfGMUKFCjwJ4SbzZtRq+UezsNdjKcgsj415gbgFGcr5kndRY1gsxWjnF8gD88IALrNs5Dju4zZ3+ES+Zcpowomejb4PGuKzYbP1yoZsWIs28MSzVVRx16aOUWBy+/xKNv+xHkyW3llyHsTZb+vzdRrYKAhitsT3CjOylF8SRB/MlA8jvSEkaYdJ8k5dPY/2ONj+2jUEoX7Io/lB3zuvtlfkB90bBSIff+f5a8doS1Pondk6lWqPFw8/Cz9E2ok42fg5rXAvNEQoJ+3wQIAaK3n1IABzQ0QMM2OI8+WYd05Ni3pIqMXi419bYxtU00xppJBND3XgcwtbyQRtjmjA2vYWJRwW7VGJ3pT3uuwXLYSgH5+DX3Mj3eDeude3iZ32Zft4tL7ASZOje0/RRqbmG6VP5L5UfbJD8KepHRAN96R67E1J5/zSYKIRz/Ulljn6dIm2WfonvWGS7ZySwh9OI4EZnje2rMLvGwEjN83ZwuF0UgOmE8H+BD5e3g88F9nNEhZzfsMLDD9OThxKZaGtwbFg7dgfwgFlLPz1GFYm/dLkUCWes="

      addons:
        coverity_scan:
        project:
        name: "2trill2spill/nextgen"
        description: "Build submitted via Travis CI"
        notification_email: hbowden@securelabsllc.com
        build_command_prepend: "./setup.sh"
        build_command:   "make -j 4"
        branch_pattern: coverity_scan

before_install:
  - brew update
  - brew outdated automake || brew upgrade automake

script: chmod u+x setup.sh && ./setup.sh && make
